config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :home, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/weather_temperature.rb
class WeatherTemperature < ApplicationRecord
  attr_accessor :remote_loaded

  def time_until_next_sync
    ((expired_at.to_datetime - DateTime.current) * 24 * 60).to_i
  end

  def update_with_open_weather(data)
    self.remote_loaded = true
    self.location = data.name
    self.temp = data.main.temp_f
    self.feels_like = data.main.feels_like_f
    self.temp_max = data.main.temp_max_f
    self.temp_min = data.main.temp_min_f
    self.expired_at = DateTime.current + 30.minutes
    self.save
  end

  class << self
    def load_from_open_weather(zip)
      ow_client = OpenWeather::Client.new(api_key: Rails.application.credentials.open_weather_api_key)
      ow_client.current_weather(zip: zip)
    end

    def current_weather_for(zip)
      weather_temp = self.find_or_initialize_by(zip_code: zip)
      return weather_temp if weather_temp.persisted? && weather_temp.expired_at > DateTime.current

      data = load_from_open_weather(zip)
      return if data.nil?

      weather_temp.update_with_open_weather(data)
      weather_temp
    rescue Exception => e
      return nil
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :location_term

  def index
    unless location_term.blank?
      @weather_temperature = WeatherTemperature.current_weather_for(location_term)
    end
  end

  private

  def location_term
    params[:location]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= form_tag home_index_path, method: :get, html: { class: "w-100" } do |f| %>
  <div class="input-group">
    <%= text_field_tag :location, location_term, placeholder: "Zip code (US only)", class: "form-control" %>
    <%= submit_tag "Search", class: "btn btn-secondary" %>
  </div>
<% end %>

<hr />

<% unless location_term.blank? %>
  <% if @weather_temperature.nil? %>
    <div class="alert alert-light" role="alert">Location not found</div>
  <% else %>
    <%= render @weather_temperature %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="light">
  <head>
    <title>Weather Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    <%= javascript_importmap_tags %>
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <h3 class="float-md-start mb-0">Wheather Demo</h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
            <a class="nav-link fw-bold py-1 px-0" href="#">About</a>
            <a class="nav-link fw-bold py-1 px-0" href="#">Contact</a>
          </nav>
        </div>
      </header>

      <main class="px-3">
        <%= yield %>
      </main>

      <footer class="mt-auto text-white-50">
        <p>
          <%= link_to "Source Code", "https://github.com/belguzmani/weather-demo", class: "text-light", target: "_blank" %>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/weather_temperatures/_weather_temperature.html.erb
<div class="card shadow-0 border">
  <div class="card-body p-4">

    <h4 class="mb-1 sfw-normal"><%= @weather_temperature.location %></h4>
    <p class="mb-2">Current temperature: <strong><%= @weather_temperature.temp %>°F</strong></p>
    <p>Feels like: <strong><%= @weather_temperature.feels_like %>°C</strong></p>
    <p>
      Max: <strong><%= @weather_temperature.temp_max %>°C</strong>,
      Min: <strong><%= @weather_temperature.temp_min %>°C</strong>
    </p>

    <% if @weather_temperature.remote_loaded %>
      <small>Just Synced</small>
    <% else %>
      <small>
        Cached (Will sync in <%= @weather_temperature.time_until_next_sync %> mins)
      </small>
    <% end %>
  </div>
</div>